<!-- Generated by @canonical/summon-component:svelte v0.36.0 -->

<script lang="ts">
  import { Button, Popover } from "@canonical/svelte-ds-app-launchpad";
  import type { PopoverMethods } from "@canonical/svelte-ds-app-launchpad";
  import { MenuContextualIcon } from "@canonical/svelte-icons";
  import { SvelteMap } from "svelte/reactivity";
  import { ContextualMenuContent } from "../ContextualMenuContent/index.js";
  import { Tab } from "./common/index.js";
  import type { TableViewBarItemProps, TableViewBarProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds table-view-bar";

  let {
    class: className,
    items,
    current,
    trailing,
    label,
    ...rest
  }: TableViewBarProps = $props();

  const tabSizes = new SvelteMap<string, number>();
  const selectedTabIndex = $derived(
    items.findIndex(({ key }) => key === current),
  );
  const selectedTab: TableViewBarItemProps | undefined = $derived(
    items[selectedTabIndex],
  );
  const selectedTabWidth = $derived(
    selectedTab ? (tabSizes.get(selectedTab.key) ?? 0) : 0,
  );

  let trailingWidth = $state(0);

  let menuPopoverMethods = $state<PopoverMethods>();
</script>

<div class={[componentCssClassName, className]} {...rest}>
  <nav aria-label={label}>
    <ul>
      {#each items as { key, ...item }, index (key)}
        {const isSelectedBefore = $derived(
          selectedTabIndex !== -1 && selectedTabIndex < index,
        )}
        {const isSelectedAfter = $derived(
          selectedTabIndex !== -1 && selectedTabIndex > index,
        )}
        <Tab
          {...item}
          current={index === selectedTabIndex}
          bind:offsetWidth={
            () => null, (width) => tabSizes.set(key, width ?? 0)
          }
          insetInlineEnd={trailingWidth}
          scrollMarginInlineStart={isSelectedBefore ? selectedTabWidth : 0}
          scrollMarginInlineEnd={(isSelectedAfter ? selectedTabWidth : 0) +
            trailingWidth}
        />
      {/each}
    </ul>
  </nav>
  <div class="trailing" bind:offsetWidth={trailingWidth}>
    <Popover
      position="block-end span-inline-start"
      bind:this={menuPopoverMethods}
    >
      {#snippet trigger(triggerProps)}
        <Button {...triggerProps} severity="base" aria-label="{label} menu">
          {#snippet iconLeft()}
            <MenuContextualIcon />
          {/snippet}
        </Button>
      {/snippet}
      <ContextualMenuContent>
        <!-- 
          - Without a wrapping `nav` to avoid duplicated identical landmarks.
          - role="list", because safari drops the list semantics for list-style: none elements if they are not in a nav: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/list-style#accessibility
        -->
        <ul role="list">
          {#each items as { key, href, onclick, ...rest }, index (key)}
            <li>
              <ContextualMenuContent.ButtonItem
                {href}
                aria-current={index === selectedTabIndex ? "page" : undefined}
                onclick={(event) => {
                  onclick?.(event);
                  menuPopoverMethods?.hidePopover();
                }}
                {...rest}
              />
            </li>
          {/each}
        </ul>
      </ContextualMenuContent>
    </Popover>
    {@render trailing?.()}
  </div>
</div>

<!-- @component
`TableViewBar` displays a horizontally scrollable set of links switching between views of the same table, plus trailing actions. The tabs are also duplicated into a contextual menu so every view stays reachable when the bar overflows.

## Example Usage
```svelte
<TableViewBar
  label="Package views"
  current="all"
  items={[
    { key: "all", text: "All packages", href: "?" },
    { key: "my-uploads", text: "My uploads", href: "?view=my-uploads" },
  ]}
>
  {#snippet trailing()}
    <Button severity="base">Settings</Button>
  {/snippet}
</TableViewBar>
```
-->
