// Generated by @canonical/summon-component:svelte v0.36.0

import type { Snippet } from "svelte";
import type { HTMLAnchorAttributes, SvelteHTMLElements } from "svelte/elements";

type BaseProps = Omit<SvelteHTMLElements["div"], "children">;

export interface TableViewBarProps extends BaseProps {
  /** The tabs to display, in the order they should appear */
  items: TableViewBarItemProps[];
  /** The `key` of the currently selected item. If no item matches, no tab is marked as current. */
  current?: string;
  /**
   * The content to display at the end of the bar, after the tabs. Usually a set of action buttons.
   **/
  trailing?: Snippet<[]>;
  /** The accessible label for the tab navigation */
  label: string;
}

export interface TableViewBarItemProps extends Omit<
  HTMLAnchorAttributes,
  "href" | "children" | "type" | "aria-current"
> {
  /** The URL to navigate to when the item is clicked */
  href: NonNullable<HTMLAnchorAttributes["href"]>;
  /** The text to display for the item */
  text: string;
  /** A key for the item, used for tracking in lists and matching the current item. Must be unique among the items. */
  key: string;
}
