pipeline:
  - test

jobs:
  test:
    architectures: amd64
    series: focal
    snaps:
      - name: bun-js
        classic: false
    run: |
      bun install
      bunx playwright install
      bun run test
