overrides:
  # Via @sveltejs/kit: https://github.com/sveltejs/kit/blob/main/packages/kit/package.json#L25
  cookie@<0.7.0: 0.7.2

patchedDependencies:
  markdown-actions@1.1.2: patches/markdown-actions@1.1.2.patch
