<!-- Generated by @canonical/summon-component:svelte v0.43.0 -->

<script lang="ts">
  import type { MeterProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds meter";

  let { class: className, criticality, ...rest }: MeterProps = $props();
</script>

<meter class={[componentCssClassName, className, criticality]} {...rest}>
</meter>
