<!-- Generated by @canonical/summon-component:svelte v0.43.0 -->

<script lang="ts" module>
  import { MODIFIER_FAMILIES } from "@canonical/svelte-ds-app-launchpad";
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import Meter from "./Meter.svelte";

  const { Story } = defineMeta({
    title: "Launchpad Components/Meter",
    component: Meter,
    tags: ["autodocs"],
    args: { min: 0, max: 100, value: 50 },
  });
</script>

<Story name="Default">
  {#snippet template(args)}
    <Meter {...args} />
  {/snippet}
</Story>

<Story
  name="Criticalities"
  argTypes={{
    criticality: { table: { disable: true } },
    min: { table: { disable: true } },
    max: { table: { disable: true } },
    value: { table: { disable: true } },
  }}
>
  {#snippet template(args)}
    {#each [undefined, ...MODIFIER_FAMILIES.criticality] as criticality, index (criticality)}
      <div class="row">
        <Meter
          style="width: 186px"
          {...args}
          value={(index + 1) * 20}
          {criticality}
        />
        {criticality ?? "default"}
      </div>
    {/each}
  {/snippet}
</Story>
