// Generated by @canonical/summon-component:svelte v0.43.0

import type { Locator } from "@vitest/browser/context";
import type { ComponentProps } from "svelte";
import { describe, expect, it } from "vitest";
import { render } from "vitest-browser-svelte";
import type { RenderResult } from "vitest-browser-svelte";
import Component from "./Meter.svelte";

describe("Meter component", () => {
  const baseProps = {
    min: 0,
    max: 100,
    value: 50,
  } satisfies ComponentProps<typeof Component>;

  it("renders", async () => {
    const page = await render(Component, { ...baseProps });
    const meter = meterLocator(page);
    await expect.element(meter).toBeInTheDocument();
    await expect.element(meter).toBeVisible();
    await expect.element(meter).toHaveAttribute("min", "0");
    await expect.element(meter).toHaveAttribute("max", "100");
    await expect.element(meter).toHaveAttribute("value", "50");
  });

  describe("attributes", () => {
    it.each([
      ["id", "test-id"],
      ["aria-label", "test-aria-label"],
    ])("applies %s", async (attribute, expected) => {
      const page = await render(Component, {
        ...baseProps,
        [attribute]: expected,
      });
      await expect
        .element(meterLocator(page))
        .toHaveAttribute(attribute, expected);
    });

    it("applies classes", async () => {
      const page = await render(Component, {
        ...baseProps,
        criticality: "information",
        class: "test-class",
      });
      const meter = meterLocator(page);
      await expect.element(meter).toHaveClass("test-class");
      await expect.element(meter).toHaveClass("ds");
      await expect.element(meter).toHaveClass("meter");
      await expect.element(meter).toHaveClass("information");
    });

    it("applies style", async () => {
      const page = await render(Component, {
        ...baseProps,
        style: "color: orange;",
      });
      await expect.element(meterLocator(page)).toHaveStyle({ color: "orange" });
    });
  });
});

function meterLocator(page: RenderResult<typeof Component>): Locator {
  return page.getByRole("meter");
}
