// Generated by @canonical/summon-component:svelte v0.43.0

import { render } from "@canonical/svelte-ssr-test";
import type { RenderResult } from "@canonical/svelte-ssr-test";
import type { ComponentProps } from "svelte";
import { describe, expect, it } from "vitest";
import Component from "./Meter.svelte";

describe("Meter SSR", () => {
  const baseProps = {
    min: 0,
    max: 100,
    value: 50,
  } satisfies ComponentProps<typeof Component>;

  describe("basics", () => {
    it("doesn't throw", () => {
      expect(() => {
        render(Component, { props: { ...baseProps } });
      }).not.toThrow();
    });

    it("renders", () => {
      const page = render(Component, { props: { ...baseProps } });
      const meter = meterLocator(page);
      expect(meter).toBeInstanceOf(page.window.HTMLMeterElement);
      expect(meter.getAttribute("min")).toBe("0");
      expect(meter.getAttribute("max")).toBe("100");
      expect(meter.getAttribute("value")).toBe("50");
    });
  });

  describe("attributes", () => {
    it.each([
      ["id", "test-id"],
      ["aria-label", "test-aria-label"],
    ])("applies %s", (attribute, expected) => {
      const page = render(Component, {
        props: { ...baseProps, [attribute]: expected },
      });
      expect(meterLocator(page).getAttribute(attribute)).toBe(expected);
    });

    it("applies classes", () => {
      const page = render(Component, {
        props: {
          class: "test-class",
          criticality: "information",
          ...baseProps,
        },
      });
      const meter = meterLocator(page);
      expect(meter.classList).toContain("test-class");
      expect(meter.classList).toContain("ds");
      expect(meter.classList).toContain("meter");
      expect(meter.classList).toContain("information");
    });

    it("applies style", () => {
      const page = render(Component, {
        props: { style: "color: orange;", ...baseProps },
      });
      expect(meterLocator(page).style.color).toBe("orange");
    });
  });
});

function meterLocator(page: RenderResult): HTMLElement {
  return page.getByRole("meter");
}
