// Generated by @canonical/summon-component:svelte v0.43.0

import type { ModifierFamily } from "@canonical/svelte-ds-app-launchpad";
import type { SvelteHTMLElements } from "svelte/elements";

type BaseProps = SvelteHTMLElements["meter"];

export type MeterProps = BaseProps & ModifierFamily<"criticality">;
