<!-- Generated by @canonical/summon:component-svelte v0.1.0 -->

<script lang="ts">
  import { InputPrimitive } from "../../../common/InputPrimitive/index.js";
  import { getPaginationContext } from "../../context.js";
  import type { PageInputProps } from "./types";
  import "./styles.css";

  const componentCssClassName = "ds pagination-page-input";

  let {
    id: idProp,
    class: className,
    style,
    value = $bindable(),
    totalPages,
    "data-testid": dataTestId,
    ...rest
  }: PageInputProps = $props();

  const paginationContext = getPaginationContext();

  const idFallback = $props.id();
  const id = $derived(idProp || idFallback);
</script>

<div
  class={[componentCssClassName, className]}
  {style}
  data-testid={dataTestId}
>
  <label for={id} class="visually-hidden">Page:</label>
  <InputPrimitive
    {id}
    bind:value
    type="number"
    aria-controls={paginationContext.tableId}
    min="1"
    max={totalPages}
    autocomplete="off"
    disabled={totalPages === 1}
    {...rest}
  />
  <span>of {totalPages} Page{totalPages === 1 ? "" : "s"}</span>
</div>
