<script lang="ts" module>
  // Generated by @canonical/summon:component-svelte v0.1.0
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import { setPaginationContext } from "../../context.js";
  import PageInput from "./PageInput.svelte";

  const { Story } = defineMeta({
    title: "Components/Pagination/PageInput",
    component: PageInput,
    tags: ["autodocs"],
    args: {
      totalPages: 10,
      value: 3,
    },
  });
</script>

<script lang="ts">
  setPaginationContext({
    tableId: "example-table",
  });
</script>

<Story name="Default" />
