// Generated by @canonical/summon:component-svelte v0.1.0
import type { NumberInputPrimitiveProps } from "../../../common/index.js";

export interface PageInputProps extends Omit<
  NumberInputPrimitiveProps,
  "type"
> {
  totalPages: number;
}
