// Generated by @canonical/summon-component:svelte v0.43.0

import type { ComponentProps } from "svelte";
import { describe, expect, it } from "vitest";
import { render } from "vitest-browser-svelte";
import type { RenderResult } from "vitest-browser-svelte";
import Component from "./Stat.svelte";
import {
  children,
  firstDetails,
  firstTerm,
  secondDetails,
  secondTerm,
} from "./test.fixtures.svelte";

describe("Stat component", () => {
  const baseProps = {
    children,
    "data-testid": "stat",
  } satisfies ComponentProps<typeof Component>;

  describe("basics", () => {
    it("renders terms and details in a description list", async () => {
      const page = await render(Component, { ...baseProps });
      const list = listLocator(page);
      await expect.element(list).toBeVisible();
      expect(list.element().tagName).toBe("DL");
      await expect.element(page.getByText(firstTerm)).toBeVisible();
      await expect.element(page.getByText(firstDetails)).toBeVisible();
      await expect.element(page.getByText(secondTerm)).toBeVisible();
      await expect.element(page.getByText(secondDetails)).toBeVisible();
      expect(
        Array.from(
          list.element().querySelectorAll("dt"),
          (term) => term.textContent,
        ),
      ).toEqual([firstTerm, secondTerm]);
      expect(
        Array.from(
          list.element().querySelectorAll("dd"),
          (detail) => detail.textContent,
        ),
      ).toEqual([firstDetails, secondDetails]);
    });

    it("renders without children", async () => {
      const page = await render(Component, { "data-testid": "stat" });
      await expect.element(listLocator(page)).toBeEmptyDOMElement();
    });
  });

  describe("attributes", () => {
    it("preserves the base class when a custom class is provided", async () => {
      const page = await render(Component, {
        ...baseProps,
        class: "custom-stat",
      });
      await expect
        .element(listLocator(page))
        .toHaveClass("ds", "stat", "custom-stat");
    });

    it("forwards HTML attributes to the description list", async () => {
      const page = await render(Component, {
        ...baseProps,
        id: "bug-stats",
        "aria-label": "Bug statistics",
      });
      const list = listLocator(page);
      await expect.element(list).toHaveAttribute("id", "bug-stats");
      await expect
        .element(list)
        .toHaveAttribute("aria-label", "Bug statistics");
    });
  });
});

function listLocator(page: RenderResult<typeof Component>) {
  return page.getByTestId("stat");
}
