<!-- Generated by @canonical/summon-component:svelte v0.43.0 -->

<script lang="ts">
  import type { StatProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds stat";

  let { class: className, children, ...rest }: StatProps = $props();
</script>

<dl class={[componentCssClassName, className]} {...rest}>
  {@render children?.()}
</dl>
