// Generated by @canonical/summon-component:svelte v0.43.0

import type { Snippet } from "svelte";
import type { SvelteHTMLElements } from "svelte/elements";

type BaseProps = SvelteHTMLElements["dl"];

export interface StatProps extends BaseProps {
  children?: Snippet;
}
