<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script module lang="ts">
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import { Button } from "../../Button/index.js";
  import { DialogContent } from "./index.js";

  const { Story } = defineMeta({
    title: "Components/DialogContent",
    tags: ["autodocs"],
    component: DialogContent,
  });
</script>

<Story name="Default" asChild>
  <DialogContent>
    <DialogContent.Header>
      Discard pending review?
      <DialogContent.Header.CloseButton />
    </DialogContent.Header>
    <DialogContent.Body>
      You have added 4 comments. Discarding the pending review will permanently
      delete them. Are you sure you want to continue?
    </DialogContent.Body>
    <DialogContent.Footer>
      <Button>Keep review</Button>
      <Button severity="negative">Discard review</Button>
    </DialogContent.Footer>
  </DialogContent>
</Story>
