// Generated by @canonical/summon-component:svelte v0.1.0

import { default as DialogContentRoot } from "./DialogContent.svelte";
import { Body, Footer, Header } from "./common/index.js";

const DialogContent = DialogContentRoot as typeof DialogContentRoot & {
  Header: typeof Header;
  Body: typeof Body;
  Footer: typeof Footer;
};

DialogContent.Header = Header;
DialogContent.Body = Body;
DialogContent.Footer = Footer;

export { DialogContent };
export type {
  BodyProps as DialogContentBodyProps,
  CloseButtonProps as DialogContentCloseButtonProps,
  FooterProps as DialogContentFooterProps,
  HeaderProps as DialogContentHeaderProps,
} from "./common/index.js";
export type { DialogContentProps } from "./types.js";
