/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jobs
         * @description Retrieve a list of all jobs in the system.
         *
         *     Args:
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         List[JobRead]: List of all jobs
         */
        get: operations["get_jobs_v1_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a new job in the system.
         *
         *     Args:
         *         job_in: Job creation model containing all required job parameters
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         JobRead: The created job object
         *
         *     Raises:
         *         HTTPException 502: If webhook notification fails
         */
        post: operations["create_job_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Retrieve a specific job by its ID.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         db: Database session dependency
         *
         *     Returns:
         *         JobRead: The requested job object
         *
         *     Raises:
         *         HTTPException 404: If job is not found
         */
        get: operations["get_job_v1_jobs__job_id__get"];
        /**
         * Update Job
         * @description Update an existing job's information.
         *
         *     Args:
         *         job_id: Unique identifier of the job to update
         *         job_in: Job update model containing fields to update
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         JobRead: The updated job object
         *
         *     Raises:
         *         HTTPException 404: If job is not found
         */
        put: operations["update_job_v1_jobs__job_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Retrieve the current health status of a job.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         db: Database session dependency
         *
         *     Returns:
         *         dict: Health status information including CPU, RAM, disk usage, and job
         *             status
         *
         *     Raises:
         *         HTTPException 404: If job is not found
         */
        get: operations["get_health_v1_jobs__job_id__health_get"];
        /**
         * Update Health
         * @description Update the health status of a running job.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         db: Database session dependency
         *         token: Builder token for authorization
         *         request: FastAPI request object containing health data
         *
         *     Returns:
         *         dict: The updated health status data
         *
         *     Raises:
         *         HTTPException 404: If job is not found
         */
        put: operations["update_health_v1_jobs__job_id__health_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cancel Job
         * @description Cancel a running job.
         *
         *     Args:
         *         job_id: Unique identifier of the job to cancel
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         dict: Confirmation message of job cancellation
         *
         *     Raises:
         *         HTTPException 404: If job is not found
         *         HTTPException 400: If job cannot be cancelled
         */
        put: operations["cancel_job_v1_jobs__job_id__cancel_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/object/{object_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Object
         * @description Download an artifact or object associated with a job.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         object_name: Name of the object/artifact to download
         *         db: Database session dependency
         *
         *     Returns:
         *         StreamingResponse: Stream of the requested object data with appropriate
         *             headers
         *
         *     Raises:
         *         HTTPException 404: If job is not found
         */
        get: operations["download_object_v1_jobs__job_id__object__object_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Token
         * @description Generate a JWT token for job authentication and set up SSH keys.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         request: FastAPI request object potentially containing SSH keys
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         dict: Contains the generated JWT token
         *
         *     Raises:
         *         HTTPException 404: If job is not found
         *         HTTPException 500: If SSH key generation fails
         */
        post: operations["generate_token_v1_jobs__job_id__token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api_access_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Api Access Token
         * @description Create a new API access token for service authentication.
         *
         *     Args:
         *         request: FastAPI request object with identity and optional expiration
         *         db: Database session dependency
         *         _: Internal-only access check dependency
         *
         *     Returns:
         *         JSONResponse: Contains the generated token and identity
         *
         *     Raises:
         *         HTTPException 400: If identity is missing from request
         *         HTTPException 403: If request is not from internal network
         */
        post: operations["create_api_access_token_v1_api_access_token_post"];
        /**
         * Revoke Api Access Token
         * @description Revoke an existing API access token.
         *
         *     Args:
         *         identity: Service identity associated with the token
         *         token: The token value to revoke
         *         db: Database session dependency
         *         _: Internal-only access check dependency
         *
         *     Returns:
         *         dict: Contains the revoked token and identity
         *
         *     Raises:
         *         HTTPException 403: If request is not from internal network
         *         HTTPException 404: If token is not found
         */
        delete: operations["revoke_api_access_token_v1_api_access_token_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runners/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Runner
         * @description Register a new runner.
         *
         *     Args:
         *         runner_in: Runner registration data including name and labels
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         dict: Contains the runner ID and its authentication token
         *
         *     Raises:
         *         HTTPException 500: If token generation fails
         */
        post: operations["register_runner_v1_runners_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runners/{runner_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runner Health
         * @description Get runner health status.
         *
         *     Args:
         *         runner_id: Unique identifier of the runner
         *         db: Database session dependency
         *
         *     Returns:
         *         dict: Runner health metrics including CPU, RAM, disk usage and status
         *
         *     Raises:
         *         HTTPException 404: If runner is not found
         */
        get: operations["get_runner_health_v1_runners__runner_id__health_get"];
        /**
         * Update Runner Health
         * @description Update runner health metrics.
         *
         *     Args:
         *         runner_id: Unique identifier of the runner
         *         request: FastAPI request object containing health metrics
         *         db: Database session dependency
         *         token: Runner token for authorization
         *
         *     Returns:
         *         dict: Success indicator
         *
         *     Raises:
         *         HTTPException 404: If runner is not found
         */
        put: operations["update_runner_health_v1_runners__runner_id__health_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint providing basic API information.
         *
         *     Returns:
         *         dict: Basic API information including:
         *             - message: API identification
         *             - version: Current API version
         *             - status: Running status
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for monitoring service status.
         *
         *     This endpoint can be used by monitoring tools and load balancers to
         *     verify the service is operational.
         *
         *     Returns:
         *         dict: Contains status indicating service health
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreate
         * @description Job creation model.
         */
        JobCreate: {
            /** Repository Url */
            repository_url?: string | null;
            /** Repository Ref */
            repository_ref?: string | null;
            /** Architecture */
            architecture: string;
            /** Base Series */
            base_series?: string;
            /** Commands */
            commands?: unknown[] | null;
            /** Secrets */
            secrets?: {
                [key: string]: unknown;
            } | null;
            /** Environment */
            environment?: {
                [key: string]: unknown;
            } | null;
            /** Artifact Path */
            artifact_path?: string | null;
            /** Topology */
            topology?: string | null;
            /** Vm Ip */
            vm_ip?: string | null;
            /** Vm Size */
            vm_size?: string | null;
            /** Private */
            private?: boolean | null;
            /**
             * Status
             * @default PENDING
             */
            status: string | null;
            /** Artifact Urls */
            artifact_urls?: unknown[] | null;
            /** Log Urls */
            log_urls?: unknown[] | null;
        };
        /**
         * JobRead
         * @description Job read model with all fields.
         */
        JobRead: {
            /** Requested By */
            requested_by: string;
            /** Repository Url */
            repository_url?: string | null;
            /** Repository Ref */
            repository_ref?: string | null;
            /** Architecture */
            architecture: string;
            /** Base Series */
            base_series: string;
            /** Commands */
            commands?: unknown[] | null;
            /** Secrets */
            secrets?: {
                [key: string]: unknown;
            } | null;
            /** Environment */
            environment?: {
                [key: string]: unknown;
            } | null;
            /** Artifact Path */
            artifact_path?: string | null;
            /** Topology */
            topology?: string | null;
            /** Vm Ip */
            vm_ip?: string | null;
            /** Vm Size */
            vm_size?: string | null;
            /** Private */
            private?: boolean;
            /**
             * Status
             * @default PENDING
             */
            status: string | null;
            /** Artifact Urls */
            artifact_urls?: unknown[] | null;
            /** Log Urls */
            log_urls?: unknown[] | null;
            /** Id */
            id: number;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * JobUpdate
         * @description Job update model.
         */
        JobUpdate: {
            /** Requested By */
            requested_by?: string;
            /** Status */
            status?: string | null;
            /** Vm Ip */
            vm_ip?: string | null;
            /** Artifact Urls */
            artifact_urls?: unknown[] | null;
            /** Log Urls */
            log_urls?: unknown[] | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * RunnerCreate
         * @description Runner creation model.
         */
        RunnerCreate: {
            /** Name */
            name: string;
            /** Labels */
            labels: string[];
        };
        /** RunnerHealthResponse */
        RunnerHealthResponse: {
            /** Label */
            label: string;
            /** Cpu Usage */
            cpu_usage: string;
            /** Ram Usage */
            ram_usage: string;
            /** Disk Usage */
            disk_usage: string;
            /** Status */
            status: string;
            /** Deletable */
            deletable: boolean;
        };
        /** RunnerHealthUpdateResponse */
        RunnerHealthUpdateResponse: {
            /** Message */
            message: string;
        };
        /** RunnerRegisterResponse */
        RunnerRegisterResponse: {
            /** Id */
            id: number;
            /** Token */
            token: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type JobCreate = components['schemas']['JobCreate'];
export type JobRead = components['schemas']['JobRead'];
export type JobUpdate = components['schemas']['JobUpdate'];
export type RunnerCreate = components['schemas']['RunnerCreate'];
export type RunnerHealthResponse = components['schemas']['RunnerHealthResponse'];
export type RunnerHealthUpdateResponse = components['schemas']['RunnerHealthUpdateResponse'];
export type RunnerRegisterResponse = components['schemas']['RunnerRegisterResponse'];
export type ValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    get_jobs_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"][];
                };
            };
        };
    };
    create_job_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_v1_jobs__job_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_v1_jobs__job_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_health_v1_jobs__job_id__health_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_v1_jobs__job_id__cancel_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_object_v1_jobs__job_id__object__object_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
                object_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_token_v1_jobs__job_id__token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_access_token_v1_api_access_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    revoke_api_access_token_v1_api_access_token_delete: {
        parameters: {
            query: {
                identity: string;
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_runner_v1_runners_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunnerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runner_health_v1_runners__runner_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_runner_health_v1_runners__runner_id__health_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerHealthUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
