/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jobs
         * @description Retrieve a list of all jobs in the system.
         *
         *     Args:
         *         tags: Optional list of tags to filter jobs by (AND logic)
         *         architecture: Optional architecture to filter jobs by
         *         requested_by: Optional user identity to filter jobs by
         *         base_series: Optional base series to filter jobs by
         *         status: Optional job status to filter jobs by
         *         private: Optional flag to filter by privacy status
         *         repository_url: Optional repository URL to filter jobs by
         *         sort: Optional field to sort by (prefix with - for descending)
         *         limit: Optional number of records to return
         *         offset: Optional number of records to skip
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         JobsListResponse: Paginated response with metadata and jobs data
         *
         *     Raises:
         *         HTTPException 401: If authorization token is invalid or missing
         *         HTTPException 400: If sort field is invalid
         */
        get: operations["get_jobs_v1_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a new job in the system.
         *
         *     Args:
         *         job_in: Job creation model containing all required job parameters
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         dict: Contains the status_url for the created job
         *
         *     Raises:
         *         HTTPException 400: If invalid tag format is provided
         *         HTTPException 401: If authorization token is invalid or missing
         */
        post: operations["create_job_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Retrieve a specific job by its ID.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         db: Database session dependency
         *         token: Optional API access token for authorization (required for
         *         private jobs)
         *
         *     Returns:
         *         JobRead: The requested job object
         *
         *     Raises:
         *         HTTPException 404: If job is not found
         *         HTTPException 401: If job is private and no valid token is provided
         *         HTTPException 403: If user doesn't have permission to view private job
         */
        get: operations["get_job_v1_jobs__job_id__get"];
        /**
         * Update Job
         * @description Update an existing job's priority.
         *
         *     Only admin users can update job priority.
         *
         *     Args:
         *         job_id: Unique identifier of the job to update
         *         job_in: Job priority update model containing priority field
         *         db: Database session dependency
         *         token: API access token for authorization (must have admin role)
         *
         *     Returns:
         *         JobRead: The updated job object
         *
         *     Raises:
         *         HTTPException 400: If job status is not PENDING
         *         HTTPException 401: If authorization token is invalid or missing
         *         HTTPException 403: If user does not have admin role
         *         HTTPException 404: If job is not found
         */
        put: operations["update_job_v1_jobs__job_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Retrieve the current health status of a job.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         db: Database session dependency
         *
         *     Returns:
         *         dict: Health status information including CPU, RAM, disk usage, and job
         *             status
         *
         *     Raises:
         *         HTTPException 401: If authorization token is invalid or missing
         *         HTTPException 404: If job is not found or not active/executing
         */
        get: operations["get_health_v1_jobs__job_id__health_get"];
        /**
         * Update Health
         * @description Update the health status of a running job.
         *
         *     This endpoint accepts health data and immediately returns 200 OK.
         *     All processing is done asynchronously in a background task.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         request: FastAPI request object containing health data
         *         background_tasks: FastAPI background tasks for async operations
         *         db: Database session dependency
         *         token: Builder token for authorization
         *
         *     Returns:
         *         dict: Acknowledgment of health update receipt
         *
         *     Raises:
         *         HTTPException 401: If builder token is invalid or missing
         *         HTTPException 404: If job is not found
         */
        put: operations["update_health_v1_jobs__job_id__health_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cancel Job
         * @description Cancel a running job.
         *
         *     Args:
         *         job_id: Unique identifier of the job to cancel
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         dict: Confirmation message of job cancellation
         *
         *     Raises:
         *         HTTPException 400: If job cannot be cancelled or is already in final
         *             state
         *         HTTPException 401: If job is private and no valid token is provided
         *         HTTPException 403: If user doesn't have permission to cancel private
         *             job
         *         HTTPException 404: If job is not found
         */
        put: operations["cancel_job_v1_jobs__job_id__cancel_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/object/{object_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Object
         * @description Download an artifact, log, or metadata file associated with a job.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         object_name: Path to the object, with format: {type}/{filename}
         *                      where type is 'artifact', 'log', or 'metadata'
         *                      (URL-encoded). Also supports legacy format without type.
         *         inline: If True, display inline in browser
         *                 (Content-Disposition: inline) and force text/plain for
         *                 files listed in the job's log_urls. Defaults to False.
         *         omit_content_length: If True, do not include Content-Length header.
         *         db: Database session dependency
         *
         *     Returns:
         *         StreamingResponse: Stream of the requested object data with appropriate
         *             headers
         *
         *     Raises:
         *         HTTPException 401: If job is private and no valid token is provided
         *         HTTPException 403: If user doesn't have permission to view private job
         *                            or access validation fails
         *         HTTPException 404: If job or object is not found
         *         HTTPException 500: If object cannot be accessed or S3 error occurs
         */
        get: operations["download_object_v1_jobs__job_id__object__object_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get Object Metadata
         * @description Get metadata (headers only) for an artifact or object associated with a
         *     job.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         object_name: Name of the object/artifact to get metadata for
         *             (URL-encoded)
         *         db: Database session dependency
         *         token: Optional API access token for authorization (required for
         *             private jobs)
         *
         *     Returns:
         *         JSONResponse: Empty response with Content-Type and Content-Length
         *             headers
         *
         *     Raises:
         *         HTTPException 404: If job or object is not found
         *         HTTPException 401: If job is private and no valid token is provided
         *         HTTPException 403: If user doesn't have permission to view private job
         *                            or access validation fails
         *         HTTPException 500: If object cannot be accessed
         */
        head: operations["get_object_metadata_v1_jobs__job_id__object__object_name__head"];
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/artifacts/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download All Artifacts
         * @description Download all artifacts for a job as a single zip file.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         db: Database session dependency
         *         token: Optional API access token for authorization (required for
         *             private jobs)
         *
         *     Returns:
         *         StreamingResponse: Stream of a zip file containing all job artifacts
         *
         *     Raises:
         *         HTTPException 401: If job is private and no valid token is provided
         *         HTTPException 403: If user doesn't have permission to view private job
         *         HTTPException 404: If job is not found or has no artifacts
         *         HTTPException 500: If artifacts cannot be accessed or S3 error occurs
         */
        get: operations["download_all_artifacts_v1_jobs__job_id__artifacts_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Token
         * @description Generate a JWT token for job authentication and set up SSH keys.
         *
         *     SSH keys are now stored in the database with encryption for the private
         *     key, enabling multi-instance deployments without shared filesystem
         *     requirements.
         *
         *     Args:
         *         job_id: Unique identifier of the job
         *         request: FastAPI request object potentially containing SSH keys
         *         db: Database session dependency
         *         token: API access token for authorization
         *
         *     Returns:
         *         dict: Contains the generated JWT token
         *
         *     Raises:
         *         HTTPException 401: If authorization token is invalid or missing
         *         HTTPException 404: If job is not found
         *         HTTPException 500: If SSH key generation fails
         */
        post: operations["generate_token_v1_jobs__job_id__token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api_access_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Api Access Token
         * @description Create a new API access token for service authentication.
         *
         *     Args:
         *         request: FastAPI request object with identity and optional expiration
         *         db: Database session dependency
         *         _: Internal-only access check dependency
         *
         *     Returns:
         *         JSONResponse: Contains the generated token and identity
         *
         *     Raises:
         *         HTTPException 400: If identity is missing from request
         *         HTTPException 403: If request is not from internal network or token is
         *             invalid
         */
        post: operations["create_api_access_token_v1_api_access_token_post"];
        /**
         * Revoke Api Access Token
         * @description Revoke an existing API access token.
         *
         *     Args:
         *         identity: Service identity associated with the token
         *         token: The token value to revoke
         *         db: Database session dependency
         *         _: Internal-only access check dependency
         *
         *     Returns:
         *         dict: Contains the revoked token and identity
         *
         *     Raises:
         *         HTTPException 403: If request is not from internal network or token is
         *             invalid
         *         HTTPException 404: If token is not found
         */
        delete: operations["revoke_api_access_token_v1_api_access_token_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runners/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Runner
         * @description Register a new runner.
         *
         *     Args:
         *         runner_in: Runner registration data including name and labels
         *         db: Database session dependency
         *
         *     Returns:
         *         dict: Contains the runner ID and its authentication token
         *
         *     Raises:
         *         HTTPException 500: If token generation fails
         */
        post: operations["register_runner_v1_runners_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runners/{runner_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runner Health
         * @description Get runner health status.
         *
         *     Args:
         *         runner_id: Unique identifier of the runner
         *         db: Database session dependency
         *
         *     Returns:
         *         dict: Runner health metrics including CPU, RAM, disk usage and status
         *
         *     Raises:
         *         HTTPException 404: If runner is not found
         */
        get: operations["get_runner_health_v1_runners__runner_id__health_get"];
        /**
         * Update Runner Health
         * @description Update runner health metrics.
         *
         *     This endpoint accepts health data and immediately returns 200 OK.
         *     All processing is done asynchronously in a background task.
         *
         *     Args:
         *         runner_id: Unique identifier of the runner
         *         request: FastAPI request object containing health metrics
         *         health_data: Health data sent by the runner
         *         background_tasks: FastAPI background tasks for async operations
         *         _: Runner token for authorization
         *
         *     Returns:
         *         dict: Acknowledgment of health update receipt
         */
        put: operations["update_runner_health_v1_runners__runner_id__health_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runners/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runners
         * @description List all runners that exist in OpenStack (admins only).
         *
         *     Returns:
         *         list: List of runners that exist in OpenStack
         */
        get: operations["list_runners_v1_runners_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runners/{runner_id}/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild Runner Admin Only
         * @description Force rebuild a runner (admins only).
         *
         *     This endpoint forcefully rebuilds a runner regardless of its status.
         *     If the runner has an assigned job, that job will be marked as FAILED
         *     before the rebuild proceeds.
         *
         *     Access control:
         *         - Requires a valid API access token
         *         - Token must have the `admin` role
         */
        post: operations["rebuild_runner_admin_only_v1_runners__runner_id__rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint providing basic API information.
         *
         *     Supports both GET and HEAD requests. HEAD requests are commonly
         *     used by monitoring tools and curl -I to check service status.
         *
         *     Returns:
         *         dict: Basic API information including:
         *             - message: API identification
         *             - version: Current API version
         *             - status: Running status
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Root
         * @description Root endpoint providing basic API information.
         *
         *     Supports both GET and HEAD requests. HEAD requests are commonly
         *     used by monitoring tools and curl -I to check service status.
         *
         *     Returns:
         *         dict: Basic API information including:
         *             - message: API identification
         *             - version: Current API version
         *             - status: Running status
         */
        head: operations["root__head"];
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for monitoring service status.
         *
         *     This endpoint can be used by monitoring tools and load balancers to
         *     verify the service is operational.
         *
         *     Returns:
         *         dict: Contains status indicating service health
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Architecture
         * @description Supported CPU architectures.
         * @enum {string}
         */
        Architecture: "amd64" | "arm64" | "armel" | "armhf" | "ppc64el" | "s390x" | "riscv64" | "amd64v3" | "i386";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreate
         * @description Job creation model.
         */
        JobCreate: {
            /**
             * Title
             * @default
             * @example Build Ubuntu 24.04 image
             */
            title: string;
            /**
             * Description
             * @default
             * @example Build a hardened Ubuntu image with security patches
             */
            description: string;
            /**
             * Repository Url
             * @default
             * @example https://example.com/org/secure-images
             */
            repository_url: string;
            /**
             * Repository Ref
             * @default
             * @example main
             */
            repository_ref: string;
            /**
             * @default amd64
             * @example amd64
             */
            architecture: components["schemas"]["Architecture"];
            /**
             * @default noble
             * @example noble
             */
            base_series: components["schemas"]["Series"];
            /**
             * Commands
             * @default []
             * @example [
             *       "sudo apt-get update",
             *       "sudo apt-get install -y curl jq",
             *       "make build",
             *       "./scripts/build.sh --release"
             *     ]
             */
            commands: unknown[];
            /**
             * Proxy Settings
             * @default {}
             * @example {
             *       "policy": "permissive"
             *     }
             */
            proxy_settings: {
                [key: string]: unknown;
            };
            /**
             * Secrets
             * @default {}
             * @example {
             *       "SECRET_TOKEN": "s3cr3t_v4lu3"
             *     }
             */
            secrets: {
                [key: string]: unknown;
            };
            /**
             * Environment
             * @default {}
             * @example {
             *       "BUILD_MODE": "hardened"
             *     }
             */
            environment: {
                [key: string]: unknown;
            };
            /**
             * Artifact Path
             * @default
             * @example build/artifacts/*.tar.gz
             */
            artifact_path: string;
            /**
             * Topology
             * @default
             * @example single-node
             */
            topology: string;
            /**
             * Vm Size
             * @default
             * @example large
             */
            vm_size: string;
            /**
             * Private
             * @default false
             * @example true
             */
            private: boolean;
            /**
             * @default PENDING
             * @example FINISHED
             */
            status: components["schemas"]["JobStatus"];
            /**
             * Priority
             * @default 0
             * @example 4
             */
            priority: number;
            /**
             * Tags
             * @default []
             * @example [
             *       "security",
             *       "production"
             *     ]
             */
            tags: string[];
        };
        /**
         * JobObjectRead
         * @description Job object read model for artifacts and logs.
         */
        JobObjectRead: {
            /**
             * Id
             * @example 1
             */
            id: number;
            /**
             * Job Id
             * @example 123
             */
            job_id: number;
            /**
             * Filename
             * @example output.tar.gz
             */
            filename: string;
            /** @example artifact */
            object_type: components["schemas"]["ObjectType"];
            /**
             * Content Type
             * @example application/gzip
             */
            content_type: string;
            /**
             * Size Bytes
             * @example 1024
             */
            size_bytes?: number | null;
            /**
             * Created At
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            created_at: string;
            /**
             * Url
             * @description URL endpoint for this object
             * @example https://example.com/jobs/123/object/artifact/output.tar.gz
             */
            readonly url: string;
        };
        /**
         * JobPriorityUpdate
         * @description Job priority update model.
         *
         *     Only priority can be updated via this model, and only by admin users.
         *     This is used for the admin-only job update endpoint.
         */
        JobPriorityUpdate: {
            /**
             * Priority
             * @example 7
             */
            priority: number;
        };
        /**
         * JobRead
         * @description Job read model with all fields.
         */
        JobRead: {
            /**
             * Title
             * @default
             * @example Build Ubuntu 24.04 image
             */
            title: string;
            /**
             * Description
             * @default
             * @example Build a hardened Ubuntu image with security patches
             */
            description: string;
            /**
             * Repository Url
             * @default
             * @example https://example.com/org/secure-images
             */
            repository_url: string;
            /**
             * Repository Ref
             * @default
             * @example main
             */
            repository_ref: string;
            /**
             * @default amd64
             * @example amd64
             */
            architecture: components["schemas"]["Architecture"];
            /**
             * @default noble
             * @example noble
             */
            base_series: components["schemas"]["Series"];
            /**
             * Commands
             * @default []
             * @example [
             *       "sudo apt-get update",
             *       "sudo apt-get install -y curl jq",
             *       "make build",
             *       "./scripts/build.sh --release"
             *     ]
             */
            commands: unknown[];
            /**
             * Proxy Settings
             * @default {}
             * @example {
             *       "policy": "permissive"
             *     }
             */
            proxy_settings: {
                [key: string]: unknown;
            };
            /**
             * Secrets
             * @default {}
             * @example {
             *       "SECRET_TOKEN": "s3cr3t_v4lu3"
             *     }
             */
            secrets: {
                [key: string]: unknown;
            };
            /**
             * Environment
             * @default {}
             * @example {
             *       "BUILD_MODE": "hardened"
             *     }
             */
            environment: {
                [key: string]: unknown;
            };
            /**
             * Artifact Path
             * @default
             * @example build/artifacts/*.tar.gz
             */
            artifact_path: string;
            /**
             * Topology
             * @default
             * @example single-node
             */
            topology: string;
            /**
             * Vm Size
             * @default
             * @example large
             */
            vm_size: string;
            /**
             * Private
             * @default false
             * @example true
             */
            private: boolean;
            /**
             * @default PENDING
             * @example FINISHED
             */
            status: components["schemas"]["JobStatus"];
            /**
             * Priority
             * @default 0
             * @example 4
             */
            priority: number;
            /**
             * Tags
             * @default []
             * @example [
             *       "security",
             *       "production"
             *     ]
             */
            tags: string[];
            /**
             * Id
             * @example 123
             */
            id: number;
            /**
             * Requested By
             * @example user
             */
            requested_by: string;
            /**
             * Created At
             * Format: date-time
             * @example 2025-01-15T09:15:30.123456Z
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @example 2025-01-15T10:45:23.456789Z
             */
            updated_at: string;
            /**
             * Started At
             * @example 2025-01-15T09:20:11.987654Z
             */
            started_at?: string | null;
            /**
             * Completed At
             * @example 2025-01-15T10:45:23.456789Z
             */
            completed_at?: string | null;
            /**
             * Objects
             * @example [
             *       {
             *         "content_type": "application/gzip",
             *         "created_at": "2025-01-15T10:30:00.123456Z",
             *         "filename": "build-output.tar.gz",
             *         "id": 1,
             *         "job_id": 123,
             *         "object_type": "artifact",
             *         "size_bytes": 2048576
             *       },
             *       {
             *         "content_type": "application/json",
             *         "created_at": "2025-01-15T10:30:05.123456Z",
             *         "filename": "fetch_service_metadata.json",
             *         "id": 2,
             *         "job_id": 123,
             *         "object_type": "metadata",
             *         "size_bytes": 512
             *       },
             *       {
             *         "content_type": "application/xml",
             *         "created_at": "2025-01-15T10:30:10.123456Z",
             *         "filename": "test-results.xml",
             *         "id": 3,
             *         "job_id": 123,
             *         "object_type": "artifact",
             *         "size_bytes": 15360
             *       },
             *       {
             *         "content_type": "text/html",
             *         "created_at": "2025-01-15T10:30:15.123456Z",
             *         "filename": "coverage-report.html",
             *         "id": 4,
             *         "job_id": 123,
             *         "object_type": "artifact",
             *         "size_bytes": 51200
             *       },
             *       {
             *         "content_type": "text/plain",
             *         "created_at": "2025-01-15T10:24:00.123456Z",
             *         "filename": "job_agent.log",
             *         "id": 5,
             *         "job_id": 123,
             *         "object_type": "log",
             *         "size_bytes": 3840
             *       },
             *       {
             *         "content_type": "text/plain",
             *         "created_at": "2025-01-15T10:25:00.123456Z",
             *         "filename": "default.log",
             *         "id": 6,
             *         "job_id": 123,
             *         "object_type": "log",
             *         "size_bytes": 10240
             *       }
             *     ]
             */
            objects?: components["schemas"]["JobObjectRead"][];
            /**
             * Duration
             * @description Duration of the job in seconds. For finished jobs, this is completed_at - started_at. For in-progress jobs, this is current time - started_at. Returns None if job hasn't started.
             * @example 3600.5
             */
            readonly duration: number | null;
            /**
             * Artifact Urls
             * @description List of artifact URLs. Generated from objects table. Use objects field for full metadata.
             * @example [
             *       "https://example.com/jobs/123/object/artifact/output.tar.gz",
             *       "https://example.com/jobs/123/object/metadata/fetch_service_metadata.json"
             *     ]
             */
            readonly artifact_urls: string[];
            /**
             * Log Urls
             * @description List of log URLs. Generated from objects table. Use objects field for full metadata.
             * @example [
             *       "https://example.com/jobs/123/object/default.log"
             *     ]
             */
            readonly log_urls: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * JobStatus
         * @description Job status values.
         * @enum {string}
         */
        JobStatus: "PENDING" | "EXECUTING" | "IDLE" | "FINISHED" | "FAILED" | "CANCELLED" | "TERMINATED";
        /**
         * JobsListMetadata
         * @description Metadata for paginated jobs list response.
         */
        JobsListMetadata: {
            /**
             * Total Count
             * @example 85
             */
            total_count: number;
            /**
             * Count
             * @example 20
             */
            count: number;
            /**
             * Limit
             * @example 20
             */
            limit: number;
            /**
             * Offset
             * @default 0
             * @example 0
             */
            offset: number;
        };
        /**
         * JobsListResponse
         * @description Paginated response for jobs list.
         */
        JobsListResponse: {
            metadata: components["schemas"]["JobsListMetadata"];
            /** Data */
            data: components["schemas"]["JobRead"][];
        };
        /**
         * ObjectType
         * @description Type of object being stored in S3.
         * @enum {string}
         */
        ObjectType: "artifact" | "log" | "metadata";
        /**
         * RunnerCreate
         * @description Runner creation model.
         */
        RunnerCreate: {
            /** Name */
            name: string;
            /** Labels */
            labels: string[];
            /**
             * Cloud Name
             * @default local
             */
            cloud_name: string;
        };
        /** RunnerHealthResponse */
        RunnerHealthResponse: {
            /** Label */
            label: string;
            /** Cpu Usage */
            cpu_usage: string;
            /** Ram Usage */
            ram_usage: string;
            /** Disk Usage */
            disk_usage: string;
            /** Status */
            status: string;
            /** Deletable */
            deletable: boolean;
        };
        /**
         * RunnerHealthUpdate
         * @description Health update data received from runner or job agent.
         *
         *     Accepts any additional fields the runner provides, but requires
         *     at least vm_ip, status, and label.
         * @example {
         *       "cpu_usage": "45.2",
         *       "disk_usage": "15360",
         *       "label": "test-runner-1",
         *       "ram_usage": "2048",
         *       "status": "EXECUTING",
         *       "vm_ip": "192.168.1.100"
         *     }
         */
        RunnerHealthUpdate: {
            /** Vm Ip */
            vm_ip?: string | null;
            status: components["schemas"]["JobStatus"];
            /** Label */
            label: string;
        } & {
            [key: string]: unknown;
        };
        /** RunnerHealthUpdateResponse */
        RunnerHealthUpdateResponse: {
            /** Message */
            message: string;
        };
        /**
         * RunnerListItem
         * @description Model for runner list item.
         */
        RunnerListItem: {
            /** Id */
            id: number;
            /** Cloud Name */
            cloud_name: string;
            /** Openstack Server Id */
            openstack_server_id: string;
            status: components["schemas"]["RunnerStatus"];
            /** Job Id */
            job_id?: number | null;
            job_status?: components["schemas"]["JobStatus"] | null;
        };
        /** RunnerRegisterResponse */
        RunnerRegisterResponse: {
            /** Id */
            id: number;
            /** Token */
            token: string;
            /** Proxy */
            proxy?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RunnerStatus
         * @description Runner status values.
         * @enum {string}
         */
        RunnerStatus: "CREATING" | "IDLE" | "BUSY" | "REBUILDING" | "DELETING" | "ERROR";
        /**
         * Series
         * @description Supported Ubuntu series.
         * @enum {string}
         */
        Series: "noble" | "mantic" | "jammy" | "focal" | "bionic";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Architecture = components['schemas']['Architecture'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type JobCreate = components['schemas']['JobCreate'];
export type JobObjectRead = components['schemas']['JobObjectRead'];
export type JobPriorityUpdate = components['schemas']['JobPriorityUpdate'];
export type JobRead = components['schemas']['JobRead'];
export type JobStatus = components['schemas']['JobStatus'];
export type JobsListMetadata = components['schemas']['JobsListMetadata'];
export type JobsListResponse = components['schemas']['JobsListResponse'];
export type ObjectType = components['schemas']['ObjectType'];
export type RunnerCreate = components['schemas']['RunnerCreate'];
export type RunnerHealthResponse = components['schemas']['RunnerHealthResponse'];
export type RunnerHealthUpdate = components['schemas']['RunnerHealthUpdate'];
export type RunnerHealthUpdateResponse = components['schemas']['RunnerHealthUpdateResponse'];
export type RunnerListItem = components['schemas']['RunnerListItem'];
export type RunnerRegisterResponse = components['schemas']['RunnerRegisterResponse'];
export type RunnerStatus = components['schemas']['RunnerStatus'];
export type Series = components['schemas']['Series'];
export type ValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    get_jobs_v1_jobs_get: {
        parameters: {
            query?: {
                /** @description Filter jobs by tags (comma-separated) */
                tags?: string[] | null;
                architecture?: string | null;
                requested_by?: string | null;
                base_series?: string | null;
                status?: string | null;
                private?: boolean | null;
                repository_url?: string | null;
                /** @description Sort by field (prefix with - for descending, e.g., -created_at) */
                sort?: string | null;
                /** @description Number of records to return */
                limit?: number | null;
                /** @description Number of records to skip */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_v1_jobs__job_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPriorityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_v1_jobs__job_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_health_v1_jobs__job_id__health_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_v1_jobs__job_id__cancel_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_object_v1_jobs__job_id__object__object_name__get: {
        parameters: {
            query?: {
                /** @description Display inline in browser */
                inline?: boolean;
                /** @description Omit Content-Length header from the response */
                omit_content_length?: boolean;
            };
            header?: never;
            path: {
                job_id: number;
                object_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_metadata_v1_jobs__job_id__object__object_name__head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
                object_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_all_artifacts_v1_jobs__job_id__artifacts_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_token_v1_jobs__job_id__token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_access_token_v1_api_access_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    revoke_api_access_token_v1_api_access_token_delete: {
        parameters: {
            query: {
                identity: string;
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_runner_v1_runners_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunnerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runner_health_v1_runners__runner_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_runner_health_v1_runners__runner_id__health_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runner_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunnerHealthUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerHealthUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runners_v1_runners_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerListItem"][];
                };
            };
        };
    };
    rebuild_runner_admin_only_v1_runners__runner_id__rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
