// Generated by @canonical/summon-component:svelte v0.43.0

import type { Locator } from "@vitest/browser/context";
import type { ComponentProps } from "svelte";
import { describe, expect, it } from "vitest";
import { render } from "vitest-browser-svelte";
import type { RenderResult } from "vitest-browser-svelte";
import Component from "./Item.svelte";

describe("Item component", () => {
  const baseProps = {
    term: "Open bugs",
    details: "58",
    "data-testid": "stat-item",
  } satisfies ComponentProps<typeof Component>;

  it("renders the term and details", async () => {
    const page = await render(Component, { ...baseProps });

    await expect.element(componentLocator(page)).toBeInTheDocument();
    await expect.element(page.getByText("Open bugs")).toBeVisible();
    await expect.element(page.getByText("58")).toBeVisible();
    expect(componentLocator(page).element().querySelector("dt")).not.toBeNull();
    expect(componentLocator(page).element().querySelector("dd")).not.toBeNull();
  });

  it("renders an accessible attention marker when marked", async () => {
    const page = await render(Component, { ...baseProps, marked: true });
    const dot = componentLocator(page).element().querySelector(".stat-dot");

    expect(dot).not.toBeNull();
    expect(dot?.getAttribute("role")).toBe("img");
    expect(dot?.getAttribute("aria-label")).toBe("Attention");
    expect(dot?.hasAttribute("aria-hidden")).toBe(false);
    await expect
      .element(page.getByRole("img", { name: "Attention" }))
      .toBeVisible();
  });

  it("does not render a dot when unmarked", async () => {
    const page = await render(Component, { ...baseProps });

    expect(
      componentLocator(page).element().querySelector(".stat-dot"),
    ).toBeNull();
  });

  describe("attributes", () => {
    it.each([
      ["id", "test-id"],
      ["aria-label", "test-aria-label"],
    ])("applies %s", async (attribute, expected) => {
      const page = await render(Component, {
        ...baseProps,
        [attribute]: expected,
      });
      await expect
        .element(componentLocator(page))
        .toHaveAttribute(attribute, expected);
    });

    it("applies classes", async () => {
      const page = await render(Component, {
        ...baseProps,
        class: "test-class",
      });

      await expect.element(componentLocator(page)).toHaveClass("test-class");
      await expect.element(componentLocator(page)).toHaveClass("ds");
      await expect.element(componentLocator(page)).toHaveClass("stat-item");
    });

    it("applies style", async () => {
      const page = await render(Component, {
        ...baseProps,
        style: "color: orange;",
      });

      await expect
        .element(componentLocator(page))
        .toHaveStyle({ color: "orange" });
    });
  });
});

function componentLocator(page: RenderResult<typeof Component>): Locator {
  return page.getByTestId("stat-item");
}
