// Generated by @canonical/summon-component:svelte v0.43.0

import { render } from "@canonical/svelte-ssr-test";
import type { RenderResult } from "@canonical/svelte-ssr-test";
import type { ComponentProps } from "svelte";
import { describe, expect, it } from "vitest";
import Component from "./Item.svelte";

describe("Item SSR", () => {
  const baseProps = {
    term: "Open bugs",
    details: "58",
    "data-testid": "stat-item",
  } satisfies ComponentProps<typeof Component>;

  describe("basics", () => {
    it("doesn't throw", () => {
      expect(() => {
        render(Component, { props: { ...baseProps } });
      }).not.toThrow();
    });

    it("renders", () => {
      const page = render(Component, { props: { ...baseProps } });
      const item = componentLocator(page);

      expect(item).toBeInstanceOf(page.window.HTMLDivElement);
      expect(item.querySelector("dt")?.textContent).toBe("Open bugs");
      expect(item.querySelector("dd")?.textContent).toBe("58");
    });

    it("renders an accessible attention marker when marked", () => {
      const page = render(Component, {
        props: { ...baseProps, marked: true },
      });
      const dot = componentLocator(page).querySelector(".stat-dot");

      expect(dot).not.toBeNull();
      expect(dot?.getAttribute("role")).toBe("img");
      expect(dot?.getAttribute("aria-label")).toBe("Attention");
      expect(dot?.hasAttribute("aria-hidden")).toBe(false);
    });
  });

  describe("attributes", () => {
    it.each([
      ["id", "test-id"],
      ["aria-label", "test-aria-label"],
    ])("applies %s", (attribute, expected) => {
      const page = render(Component, {
        props: { ...baseProps, [attribute]: expected },
      });
      expect(componentLocator(page).getAttribute(attribute)).toBe(expected);
    });

    it("applies classes", () => {
      const page = render(Component, {
        props: { class: "test-class", ...baseProps },
      });
      expect(componentLocator(page).classList).toContain("test-class");
      expect(componentLocator(page).classList).toContain("ds");
      expect(componentLocator(page).classList).toContain("stat-item");
    });

    it("applies style", () => {
      const page = render(Component, {
        props: { style: "color: orange;", ...baseProps },
      });
      expect(componentLocator(page).style.color).toBe("orange");
    });
  });
});

function componentLocator(page: RenderResult): HTMLElement {
  return page.document.querySelector<HTMLElement>('[data-testid="stat-item"]');
}
