<!-- Generated by @canonical/summon-component:svelte v0.43.0 -->

<script module lang="ts">
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import { Stat } from "../../index.js";
  import Item from "./Item.svelte";

  const { Story } = defineMeta({
    title: "Launchpad Components/Stat/Item",
    component: Item,
    tags: ["autodocs"],
    args: { term: "Open bugs", details: "58", marked: false },
  });
</script>

<Story name="Default">
  {#snippet template(args)}
    <dl>
      <Item {...args} />
    </dl>
  {/snippet}
</Story>

<Story name="Marked" args={{ marked: true }}>
  {#snippet template(args)}
    <dl>
      <Item {...args} />
    </dl>
  {/snippet}
</Story>

<Story name="Direct child of Stat">
  {#snippet template(args)}
    <Stat>
      <Stat.Item {...args} />
    </Stat>
  {/snippet}
</Story>
