<!-- Generated by @canonical/summon-component:svelte v0.43.0 -->

<script lang="ts">
  import type { ItemProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds stat-item";

  let {
    term,
    details,
    marked = false,
    class: className,
    ...rest
  }: ItemProps = $props();
</script>

<div class={[componentCssClassName, className]} {...rest}>
  <dt class="stat-term">{term}</dt>
  <dd class="stat-description">
    {#if marked}<span role="img" aria-label="Attention" class="stat-dot"
      ></span>{/if}{details}
  </dd>
</div>
