// Generated by @canonical/summon-component:svelte v0.43.0

import type { SvelteHTMLElements } from "svelte/elements";

type BaseProps = Omit<SvelteHTMLElements["div"], "children">;

export interface ItemProps extends BaseProps {
  term: string;
  details: string;
  marked?: boolean;
}
