<!-- Generated by @canonical/summon-component:svelte v0.36.0 -->

<script lang="ts">
  import type { TabProps } from "./types.js";
  import "./styles.css";
  import { browser } from "$app/environment";

  const componentCssClassName = "ds table-view-bar-tab";

  let {
    class: className,
    text,
    current,
    onfocus,
    offsetWidth = $bindable(),
    insetInlineEnd = 0,
    scrollMarginInlineStart = 0,
    scrollMarginInlineEnd = 0,
    ...rest
  }: TabProps = $props();
</script>

<li
  class={[componentCssClassName, className]}
  class:current
  // Sticky only once hydrated: pinning the current tab is only safe when the scroll margins keeping other tabs clear of it have been measured.
  class:sticky={browser && current}
  bind:offsetWidth
  style:inset-inline-end="{insetInlineEnd}px"
>
  <a
    aria-current={current ? "page" : undefined}
    onfocus={(e) => {
      onfocus?.(e);
      e.currentTarget.scrollIntoView({
        // Without `block`, the default of `start` scrolls ancestor scrollports vertically in browsers that ignore `container`.
        block: "nearest",
        inline: "nearest",
        // @ts-expect-error Option exists but is new-ish (https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#container). Remove when TS upgraded.
        container: "nearest",
      });
    }}
    style:scroll-margin-inline-start="{scrollMarginInlineStart}px"
    style:scroll-margin-inline-end="{scrollMarginInlineEnd}px"
    {...rest}
  >
    {text}
  </a>
</li>
