// Hand-written type module for the `packages` API.
//
// Mirrors the shape openapi-typescript emits: an interface `paths` keyed by
// route template, each entry keyed by HTTP method, each method describing
// `parameters`, optional `requestBody`, and `responses`. When the real server
// lands, this file gets regenerated by `openapi-typescript` and consumers
// should not need to change.

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

export type Architecture =
  | "amd64"
  | "arm64"
  | "armhf"
  | "i386"
  | "ppc64el"
  | "riscv64"
  | "s390x"
  | "all";

export type Component = "main" | "universe" | "restricted" | "multiverse";

export type Pocket =
  | "Release"
  | "Security"
  | "Updates"
  | "Proposed"
  | "Backports";

export type Priority =
  | "Required"
  | "Important"
  | "Standard"
  | "Optional"
  | "Extra";

export type Urgency = "Low" | "Medium" | "High" | "Critical" | "Emergency";

export type PublishingStatus =
  | "Published"
  | "Pending"
  | "Superseded"
  | "Deleted"
  | "Obsolete";

export type VersionStatus =
  | "Published"
  | "Pending"
  | "Accepted"
  | "Unapproved"
  | "Rejected"
  | "Deleted"
  | "Superseded"
  | "New";

export type BuildStatus =
  | "success"
  | "failure"
  | "building"
  | "pending"
  | "cancelled"
  | "depwait"
  | "chrootwait";

export type CveStatus = "active" | "released" | "ignored" | "mitigated";

export type CveSeverity =
  | "untriaged"
  | "negligible"
  | "low"
  | "medium"
  | "high"
  | "critical";

export type BugImportance =
  | "Critical"
  | "High"
  | "Medium"
  | "Low"
  | "Wishlist"
  | "Undecided"
  | "Unknown";

export type BugStatus =
  | "New"
  | "Confirmed"
  | "Triaged"
  | "In Progress"
  | "Fix Committed"
  | "Fix Released"
  | "Invalid"
  | "Won't Fix"
  | "Opinion"
  | "Expired";

export type MergeProposalStatus =
  | "Work in progress"
  | "Needs review"
  | "Approved"
  | "Merged"
  | "Rejected"
  | "Superseded";

export type Series = {
  name: string;
  displayName: string;
  version: string;
};

export type Maintainer = {
  id: string;
  name: string;
  profileIcon: string;
  url?: string;
};

export type PackageRef = {
  name: string;
  version?: string;
  url?: string;
};

export type FileAsset = {
  fileName: string;
  downloadUrl: string;
  fileSize: string;
  shaChecksum?: string;
};

export type ExternalLink = {
  name: string;
  url: string;
  icon?: string;
};

export type Paginated<T> = {
  items: T[];
  total: number;
  page: number;
  size: number;
};

export type ErrorResponse = {
  detail: string;
  code?: string;
};

// ---------------------------------------------------------------------------
// Domain entities
// ---------------------------------------------------------------------------

export type SourcePackageListItem = {
  sourcePackage: {
    id: string;
    name: string;
    latestVersion: string;
    latestVersionId: string;
  };
  status: PublishingStatus;
  series: Series & { id: string };
  pocket: Pocket;
  component: Component;
  binaryPackages: Array<{
    id: string;
    name: string;
  }>;
};

export type SourcePackageDetails = {
  id: string;
  name: string;
  description: string;
  maintainer: Maintainer;
  urgency: Urgency;
  architectures: Architecture[];
  openBugCount: number;
  openQuestionsCount: number;
  changeLogCount: number;
  /** URL to the package's `+changelog` page on Launchpad (or our mirror). */
  changelogUrl?: string;
  /** Number of uploads in a non-Published state (Pending / Accepted / Unapproved / New). */
  pendingUploads?: number;
};

export type SourcePackageBinariesGroup = {
  title: string;
  description: string;
  artifacts: Array<{
    id: string;
    name: string;
    version: string;
    architecture: Architecture;
    status: PublishingStatus;
  }>;
};

export type LatestVersionInfo = {
  id: string;
  version: string;
  downloadUrl: string;
  fileName: string;
  fileSize: string;
  status: PublishingStatus;
  pocket: Pocket;
  component: Component;
  priority: Priority;
  build: string;
  source: string;
};

export type PackageUploadItem = {
  id: string;
  name: string;
  version: string;
  status: VersionStatus;
  series: Series & { id: string };
  pocket: Pocket;
  component: Component;
  uploadDateTime: string;
  links: {
    updateExcuses?: string;
    autopkgtest?: string;
  };
};

export type CurrentVersionItem = {
  id: string;
  series: Series & { id: string };
  version: string;
  pocket: Pocket;
  component: Component;
  publishedOn: string;
};

export type PackageBug = {
  id: string;
  title: string;
  importance: BugImportance;
  status: BugStatus;
  series?: Series & { id: string };
};

export type PackageCve = {
  id: string;
  title: string;
  severity: CveSeverity;
  status: CveStatus;
  publishedDate: string;
  affectedVersions: string[];
};

export type MergeProposal = {
  id: string;
  title: string;
  url: string;
  status: MergeProposalStatus;
  registrant: Maintainer;
  createdAt: string;
};

export type PackageRelationships = {
  dependedOn: PackageRef[];
  recommends: PackageRef[];
  suggests: PackageRef[];
  conflicts: PackageRef[];
  dependedBy: PackageRef[];
  recommendedBy: PackageRef[];
  suggestedBy: PackageRef[];
};

export type PpaVersion = {
  id: string;
  version: string;
  ppa: {
    name: string;
    img: string;
    url: string;
  };
  author: {
    id: string;
    name: string;
    profileImage: string;
    url: string;
  };
};

export type PackageUpstreamDetails = {
  homepage?: string;
  repositoryUrl?: string;
  bugTrackerUrl?: string;
  latestRelease?: {
    version: string;
    releasedAt: string;
    url: string;
  };
  contacts: Array<{ name: string; role: string; url?: string }>;
};

export type DebianTrackerLinks = {
  trackerUrl: string;
  btsUrl: string;
  latestDebianVersion?: string;
  latestDebianSeries?: string;
  openBugCount?: number;
};

export type SourceTreeLink = {
  distribution: string;
  packageName: string;
  url: string;
};

export type VersionDetails = {
  id: string;
  version: string;
  changelog: string;
  changes: Array<{ url: string; name: string }>;
  uploader: Maintainer;
  uploadDate: string;
  uploadDestination: string;
  originalMaintainer: Maintainer;
  section: string;
  urgency: Urgency;
  architectures: Architecture[];
};

export type VersionPublishingInfo = {
  status: PublishingStatus;
  publishDate: string;
  series: Series & { id: string };
  pocket: Pocket;
  component: Component;
  section: string;
  builds: Array<{
    name: Architecture;
    status: BuildStatus;
    url: string;
  }>;
  links: {
    updateExcuses?: string;
    autopkgtest?: string;
  };
};

export type VersionSourceFile = FileAsset;

export type VersionBinaryPackage = {
  id: string;
  name: string;
  url: string;
  description: string;
  architectures: Array<{ name: Architecture; id: string }>;
  downloadUrl: string;
};

export type VersionBuildRequirements = {
  dependencies: {
    buildDepends: PackageRef[];
    buildDependsIndep: PackageRef[];
    buildDependsArch: PackageRef[];
  };
  conflicts: {
    buildConflicts: PackageRef[];
    buildConflictsIndep: PackageRef[];
  };
};

export type BinaryPackageDetails = {
  id: string;
  name: string;
  debPackage: {
    name: string;
    size: string;
    url: string;
  };
  version: string;
  status: PublishingStatus;
  pocket: Pocket;
  component: Component;
  priority: Priority;
  build: string;
  source: string;
  relationships: PackageRelationships;
};

// ---------------------------------------------------------------------------
// User-scoped state (TASK-API-002)
// ---------------------------------------------------------------------------

export type PackagesViewsPreference = {
  defaultTabs: string[];
  myTeams: string[];
};

// ---------------------------------------------------------------------------
// Query types
// ---------------------------------------------------------------------------

/**
 * Fields every endpoint accepts (collection or detail). `distro` is the
 * `[distro]` route param threaded through every call so the mock can scope
 * data to its seeded distro; absent
 * → mock treats it as ubuntu (backwards-compat for `client.test.ts`).
 * `_inject_error` is the test-only error-path lever.
 */
export type BaseQuery = {
  distro?: string;
  /** Force a non-200 response — wired in the client for testing error paths. */
  _inject_error?: number;
};

export type CollectionQuery = BaseQuery & {
  q?: string;
  page?: number;
  size?: number;
  sort?: string;
};

export type SourcePackagesTab =
  | "all"
  | "my-uploads"
  | "latest-uploads"
  | "ubuntu-server";

export type SortOrder = "asc" | "desc";

export type SourcePackagesListQuery = Omit<CollectionQuery, "size"> & {
  /** `"all"` returns the full filtered set on a single page. */
  size?: number | "all";
  /** Alias for `q`. Either may be set; both behave identically. */
  search?: string;
  /** Tab association; defaults to `"all"`. */
  tab?: SourcePackagesTab;
  /** Sort direction; defaults to `"asc"`. Ignored when `sort` carries a `±` prefix. */
  order?: SortOrder;
  filter?: {
    status?: PublishingStatus | PublishingStatus[];
    series?: string | string[];
    pocket?: Pocket | Pocket[];
    scope?: "all" | "my";
    component?: Component | Component[];
    section?: string | string[];
    team?: string | string[];
  };
};

export type PackageBugsQuery = CollectionQuery & {
  filter?: {
    series?: string | string[];
    importance?: BugImportance | BugImportance[];
    status?: BugStatus | BugStatus[];
  };
};

export type VersionBinariesQuery = CollectionQuery;

export type PackageVersionsQuery = CollectionQuery & {
  filter?: {
    series?: string | string[];
    pocket?: Pocket | Pocket[];
    status?: VersionStatus | VersionStatus[];
  };
};

// ---------------------------------------------------------------------------
// paths interface — mirrors openapi-typescript output shape
// ---------------------------------------------------------------------------

export interface paths {
  "/health": {
    get: {
      parameters: {
        query?: BaseQuery;
        path?: never;
      };
      responses: {
        200: {
          content: {
            "application/json": { status: "ok"; timestamp: string };
          };
        };
      };
    };
  };

  "/source-packages": {
    get: {
      parameters: {
        query?: SourcePackagesListQuery;
        path?: never;
      };
      responses: {
        200: {
          content: {
            "application/json": Paginated<SourcePackageListItem>;
          };
        };
        500: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": SourcePackageDetails } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/binary-packages": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string };
      };
      responses: {
        200: {
          content: { "application/json": SourcePackageBinariesGroup };
        };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions": {
    get: {
      parameters: {
        query?: PackageVersionsQuery;
        path: { name: string };
      };
      responses: {
        200: {
          content: { "application/json": Paginated<PackageUploadItem> };
        };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions/latest": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": LatestVersionInfo } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions/current": {
    get: {
      parameters: {
        query?: CollectionQuery & {
          filter?: { series?: string | string[] };
        };
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": CurrentVersionItem[] } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions/{version}": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string; version: string };
      };
      responses: {
        200: { content: { "application/json": VersionDetails } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions/{version}/source-files": {
    get: {
      parameters: {
        query?: BaseQuery & { sort?: string };
        path: { name: string; version: string };
      };
      responses: {
        200: { content: { "application/json": VersionSourceFile[] } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions/{version}/binary-packages": {
    get: {
      parameters: {
        query?: VersionBinariesQuery;
        path: { name: string; version: string };
      };
      responses: {
        200: {
          content: { "application/json": Paginated<VersionBinaryPackage> };
        };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions/{version}/build-requirements": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string; version: string };
      };
      responses: {
        200: {
          content: { "application/json": VersionBuildRequirements };
        };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions/{version}/publishing": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string; version: string };
      };
      responses: {
        200: { content: { "application/json": VersionPublishingInfo } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/versions/{version}/upstream": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string; version: string };
      };
      responses: {
        200: { content: { "application/json": ExternalLink[] } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/ppa-versions": {
    get: {
      parameters: {
        query?: CollectionQuery;
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": Paginated<PpaVersion> } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/bugs": {
    get: {
      parameters: {
        query?: PackageBugsQuery;
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": Paginated<PackageBug> } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/cves": {
    get: {
      parameters: {
        query?: CollectionQuery & {
          filter?: {
            severity?: CveSeverity | CveSeverity[];
            status?: CveStatus | CveStatus[];
          };
        };
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": Paginated<PackageCve> } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/merge-proposals": {
    get: {
      parameters: {
        query?: CollectionQuery;
        path: { name: string };
      };
      responses: {
        200: {
          content: { "application/json": Paginated<MergeProposal> };
        };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/relationships": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": PackageRelationships } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/upstream": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string };
      };
      responses: {
        200: {
          content: { "application/json": PackageUpstreamDetails };
        };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/debian": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": DebianTrackerLinks } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/source-packages/{name}/source": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": SourceTreeLink } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/binary-packages/{name}": {
    get: {
      parameters: {
        query?: BaseQuery;
        path: { name: string };
      };
      responses: {
        200: { content: { "application/json": BinaryPackageDetails } };
        404: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/me/source-packages": {
    get: {
      parameters: {
        query?: SourcePackagesListQuery;
        path?: never;
      };
      responses: {
        200: {
          content: {
            "application/json": Paginated<SourcePackageListItem>;
          };
        };
        400: { content: { "application/json": ErrorResponse } };
      };
    };
  };

  "/me/packages-views": {
    get: {
      parameters: {
        query?: BaseQuery;
        path?: never;
      };
      responses: {
        200: {
          content: { "application/json": PackagesViewsPreference };
        };
      };
    };
    put: {
      parameters: {
        query?: BaseQuery;
        path?: never;
      };
      requestBody: {
        content: { "application/json": PackagesViewsPreference };
      };
      responses: {
        200: {
          content: { "application/json": PackagesViewsPreference };
        };
        400: { content: { "application/json": ErrorResponse } };
      };
    };
  };
}
