name: Clean up old workflow runs

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: canonical/launchpad-actions/.github/workflows/janitor.yaml@160accd95f96dc57b4f65147fa60259afb773526 # 160accd95f96dc57b4f65147fa60259afb773526
    with:
      dry_run: false
      keep_workflows: "chromatic.yaml,publish.yaml,zizmor.yaml"
