name: Clean up old workflow runs

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: canonical/launchpad-actions/.github/workflows/janitor.yaml@f958634637cc70a6a282bf4f57b1da0a94cc2648 # f958634637cc70a6a282bf4f57b1da0a94cc2648
    with:
      dry_run: false
      keep_workflows: "chromatic.yaml,publish.yaml,zizmor.yaml"
