name: Clean up old workflow runs

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: canonical/launchpad-actions/.github/workflows/janitor.yaml@8034b2924bbd5574c339a6da8fe95e0d1c034994 # 8034b2924bbd5574c339a6da8fe95e0d1c034994
    with:
      dry_run: false
      keep_workflows: "build-rock.yaml,chromatic.yaml,zizmor.yaml"
