name: Sync with Launchpad repository

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  actions: write

jobs:
  sync:
    uses: canonical/launchpad-actions/.github/workflows/sync.yaml@160accd95f96dc57b4f65147fa60259afb773526 # 160accd95f96dc57b4f65147fa60259afb773526
    with:
      source_url: https://git.launchpad.net/launchpad-ui
