name: Sync with Launchpad repository

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  actions: write

jobs:
  sync:
    uses: canonical/launchpad-actions/.github/workflows/sync.yaml@29acf6ef813a528b94ee87f3680ad844cde6ca8f # 29acf6ef813a528b94ee87f3680ad844cde6ca8f
    with:
      source_url: https://git.launchpad.net/launchpad-ui
