name: Sync with Launchpad repository

on:
  schedule:
    # Runs every 10 minutes from 9am to 8pm
    - cron: "*/1 9-20 * * *"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Check for repository updates
        id: check_updates
        run: |
          bun add -g jsdom
          cat <<EOF > launchpad_hash.js
            const { JSDOM } = require("jsdom");
            const html = await fetch("https://git.launchpad.net/launchpad-ui").then(res => res.text());
            const dom = new JSDOM(html);
            const document = dom.window.document;
            const branchesEditAtEls = document.querySelectorAll("#cgit > div.content > table > tbody > tr > td:nth-child(4) > span");
            const branchesEditAt = Array.from(branchesEditAtEls).map(el => el.getAttribute("title"));
            branchesEditAt.sort((a, b) => new Date(a) - new Date(b))
            console.log("--------------------------------");
            console.log("Latest branch edit at:", branchesEditAt[branchesEditAt.length - 1]);
            console.log("--------------------------------");
            const hasher = new Bun.CryptoHasher("sha256");
            const key = branchesEditAt.join("\n")
            hasher.update(key);
            const hash = hasher.digest("hex");
            await Bun.write("launchpad_hash.txt", hash);
          EOF
          bun launchpad_hash.js
          echo "hash=$(cat launchpad_hash.txt)" >> $GITHUB_OUTPUT
          echo "Current Launchpad commit hash is: $(cat launchpad_hash.txt)"

      - name: Check cache for hash
        id: cache-check
        uses: actions/cache@v4
        with:
          path: launchpad_hash.txt
          key: launchpad-sync-${{ steps.check_updates.outputs.hash }}

      - name: Skip if hash is cached
        if: steps.cache-check.outputs.cache-hit == 'true'
        run: echo "No new commits found on Launchpad. Skipping sync."

      - name: Setup SSH
        if: steps.cache-check.outputs.cache-hit != 'true'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PUSH_DEPLOY_PRIVATE_KEY }}

      - name: Mirror from Launchpad to GitHub
        if: steps.cache-check.outputs.cache-hit != 'true'
        env:
          TARGET_REPO: ${{ github.repository }}
        run: |
          set -e
          echo "New commits found. Syncing from https://git.launchpad.net/launchpad-ui to ${TARGET_REPO}"

          # Clone the Launchpad repository as a mirror.
          git clone --mirror https://git.launchpad.net/launchpad-ui launchpad-ui.git
          cd launchpad-ui.git

          # Set the push URL to the GitHub repository.
          git remote set-url --push origin "git@github.com:${TARGET_REPO}.git"

          # Push all branches and tags to the GitHub repository.
          # The --mirror flag ensures all refs (branches, tags, etc.) are mirrored.
          git push --mirror --force
